### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by resatugurulu** [socialbotspy/LinkedinPy#10]
/usr/local/bin/python3.7 /Users/R/Documents/GitHub/LinkedinPy/linkedinpy/linkedinpy.py
Traceback (most recent call last):
  File "/Users/R/Documents/GitHub/LinkedinPy/linkedinpy/linkedinpy.py", line 33, in <module>
    from .database_engine import get_database
ModuleNotFoundError: No module named '__main__.database_engine'; '__main__' is not a package

Process finished with exit code 1

**Comment by ishandutta2007** [comment]
Make sure you followed https://github.com/socialbotspy/LinkedinPy#installation
steps as it is on a mc/linux
