### ISSUE TITLE
How to solve this problem？

### ISSUE THREAD

**Issue by Chandler-Song** [socialbotspy/LinkedinPy#4]
![image](https://user-images.githubusercontent.com/23094571/60151322-f04c3100-980e-11e9-9910-71341c1c74a3.png)

**Comment by ishandutta2007** [comment]
These are methods to install on mac and might work for linux as well.
But you already on windows, might not work there.

Seems like there is a different `pyenv` for windows https://pypi.org/project/pyenv-win/
Try it out and let us know, based on your feedback will update the steps for windows as well.

Incase you are very basic into programming just do the pyenv for windows separately . The following lines(ie `pyenv install 3.6.0`, `pyenv local 3.6.0`, `pip install -r requirements.txt`) should remain as it is
