### ISSUE TITLE
Best strategy to attract more to my profile

### ISSUE THREAD

**Issue by ohld** [socialbotspy/LinkedinPy#6]
Hi developers!

I'm the creator and main developer of similar automation tools but from Instagram https://github.com/instagrambot. Also, I tried to play with GitHub automation (you can check my follower counts). 

One of the best automation strategies on Instagram is to like & watch as much as you can - targeted users will see your account and will follow/like/comment you. Of course, it highly depends on the way how you target users to interact with.

The GitHub strategy for me is to follow a much as I can and wait for them to follow me back. And this kinda works.

So. My question is - what is the best strategy on Linkedin to attract more cool guys to my Linkedin page? I think my page is cool enough to be attractive, I just need more impressions. (Correct me if I am wrong, my link: https://www.linkedin.com/in/dokhlopkov/).

Current strategy on my mind is to watch other users profiles to let them receive the notification "this user just watched your profile". Will this help? If yes, how can I do it with your library?

**Comment by ishandutta2007** [comment]
Awesome @ohld, Great that you found us, lets join efforts to make open-source bots community better and bigger. As of now LinkedinPy has only features for personal profile, nothing for Linkedin Pages yet. We have written follow unfollow APIs for Github as well. Maybe we can merge efforts there too.

**Comment by ohld** [comment]
@ishandutta2007 Thanks. You can add me to your organization if you want.

But still, I've asked questions in my post, can you please answer them too?

**Comment by ishandutta2007** [comment]
@ohld Oh sorry I missed the questions part.  Best strategy according to me is to request people in your connection to recommend you, by this path you can befriend even multibillionaire CEOs or godfathers in your field. It's difficult to automate all steps of those workflow but you can automate the seeking recommendation part. But mind your too much self boasting doesn't help, if not harms it.
Watching profiles increases views but not really excite big guys send you a connect. More easy and working strategy is to send a befitting message with a very specific purpose while sending a  connect request.
None of these two are automated in LinedinPy yet.

**Comment by ohld** [comment]
@ishandutta2007 Thanks. So what is the best strategy right now if I decide something from already implemented or something from the pipeline?

**Comment by ishandutta2007** [comment]
LinkedinPy primary does:
- to grow your connections just auto connect new people auto chosen by appropriate filters in hope they will accept it.
- to grow your connections just auto connect new people from people suggested by linkedin filtered by appropriate keyword.
- to get endorsements just endorse people already in your connection in hope they will endorse you back.

Check the documentations for details, it's just one pager.

**Comment by ohld** [comment]
Great, seems that 3d and 4th are the most useful right now to not be very spammy. 

Is the `mass profile viewer` on the roadmap already? I think this will be the most valuable not-spammy script.

**Comment by ishandutta2007** [comment]
I am not too much of a fan of viewing profile, in Linkedin just numbers dont mean much to me, getting connected to the hotshots is my priority and visiting their profile won't make then connect me, it only encourages lots of useless invites for me. I dont want to spend time coding such API myself as I wont use it, however if anyone does I will be happy to merge the PR.
