### ISSUE TITLE
unknown error: cannot find Chrome binary

### ISSUE THREAD

**Issue by ankitkr554** [socialbotspy/LinkedinPy#8]
I using python3 what should i do.
<pre>Traceback (most recent call last):
  File &quot;quickstart.py&quot;, line 18, in &lt;module&gt;
    session = LinkedinPy()  # use_firefox=True)
  File &quot;/home/tikna/Desktop/bots/linkedIn/LinkedinPy/linkedinpy/linkedinpy.py&quot;, line 151, in __init__
    self.set_selenium_local_session(Settings)
  File &quot;/home/tikna/Desktop/bots/linkedIn/LinkedinPy/linkedinpy/linkedinpy.py&quot;, line 205, in set_selenium_local_session
    raise SocialPyError(err_msg)
socialcommons.exceptions.SocialPyError: ensure chromedriver is installed at /home/tikna/Desktop/bots/linkedIn/LinkedinPy/linkedIn/local/lib/python2.7/site-packages/instapy_chromedriver/chromedriver_linux64
</pre>

**Comment by ishandutta2007** [comment]
> socialcommons.exceptions.SocialPyError: ensure chromedriver is installed at /home/tikna/Desktop/bots/linkedIn/LinkedinPy/linkedIn/local/lib/python2.7/site-packages/instapy_chromedriver/chromedriver_linux64

It says python 2.7.
Seems like you have mixed it up.
To be save use pyenv or virtual env.
